kind: pipeline
type: docker
name: default

steps:
- name: motd
  image: python:3
  commands:
  - mkdir -p _salt/motds
  - cd motd-generator
  - pip install wheel
  - pip install -r requirements.txt
  - python motd-generator.py ../_salt/motds
- name: deploy
  image: registry.gitlab.com/spirostack/spiro-deploy:master
  environment:
    SPIRO_URL:
      from_secret: SPIRO_URL
    SPIRO_TOKEN:
      from_secret: SPIRO_TOKEN
  when:
    branch:
    - trunk
  commands:
  - spiro-deploy core trunk --highstate
